name: Auto Tag, Release & Publish to NuGet

on:
  push:
    branches:
      - main # Cambia a master si esa es tu rama principal
    paths:
      - '**/*.csproj'

jobs:
  release-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    defaults:
      run:
        working-directory: ./src 

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Extract Version from .csproj
      id: get_version
      working-directory: ./ 
      run: |
        CSPROJ_FILE=$(find . -name "*.csproj" -print -quit)
        echo "Archivo encontrado: $CSPROJ_FILE"
        VERSION=$(grep -oPm1 '(?<=<Version>)[^<]+' "$CSPROJ_FILE")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Versión detectada en el .csproj: $VERSION"

    - name: Check if Tag Exists
      id: check_tag
      working-directory: ./
      run: |
        if git rev-parse "v${{ steps.get_version.outputs.version }}" >/dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "El tag v${{ steps.get_version.outputs.version }} ya existe. Omitiendo despliegue."
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Restore Dependencies
      if: steps.check_tag.outputs.exists == 'false'
      run: dotnet restore RMMSoft.Mediator.sln

    - name: Build Project (Release)
      if: steps.check_tag.outputs.exists == 'false'
      run: dotnet build RMMSoft.Mediator.sln -c Release --no-restore

    - name: Push Package to NuGet
      if: steps.check_tag.outputs.exists == 'false'
      # Buscamos de forma recursiva partiendo desde la raíz del repositorio para no perder el .nupkg
      working-directory: ./
      run: |
        dotnet nuget push "**/bin/Release/**/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://nuget.org --skip-duplicate
